version: '3.1'

volumes:
  c10-postgres-data:
    driver: local
  c10-moodledata:
    driver: local

services:
  db:
    image: postgres
    container_name: c10-db
    restart: always
    environment:
      POSTGRES_DB: c10
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moodleC10123abc
    volumes:
      - c10-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    image: moodle:3.8
    container_name: c10-web
    links:
      - db
    environment:
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: c10
      MOODLE_DB_USER: postgres
      MOODLE_DB_PASS: moodleC10123abc
      MOODLE_DB_PREFIX: mdl_
      MOODLE_URL: http://localhost:8080
    volumes:
      - c10-moodledata:/var/www/moodledata
    ports:
      - "8080:80"